Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\uvicorn\__main__.py", line 4, in <module>
    uvicorn.main()
    ~~~~~~~~~~~~^^
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\click\core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\uvicorn\main.py", line 410, in main
    run(
    ~~~^
        app,
        ^^^^
    ...<45 lines>...
        h11_max_incomplete_event_size=h11_max_incomplete_event_size,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
    ~~~~~~~~~~^^
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Lib\asyncio\runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "D:\Programs\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\Programs\Python\Lib\asyncio\base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\uvicorn\config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\uvicorn\importer.py", line 22, in import_from_string
    raise exc from None
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "D:\Programs\Python\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\2.mrdom-sdr-mvp\apimain.py", line 3, in <module>
    from fastapi import FastAPI, Request
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\fastapi\routing.py", line 24, in <module>
    from fastapi import params
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\fastapi\params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\fastapi\openapi\models.py", line 4, in <module>
    from fastapi._compat import (
    ...<6 lines>...
    )
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\fastapi\_compat.py", line 21, in <module>
    from fastapi.exceptions import RequestErrorModel
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\fastapi\exceptions.py", line 3, in <module>
    from pydantic import BaseModel, create_model
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\pydantic\__init__.py", line 404, in __getattr__
    module = import_module(module_name, package=package)
  File "D:\Programs\Python\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\pydantic\main.py", line 27, in <module>
    import pydantic_core
  File "D:\2.mrdom-sdr-mvp\.venv\Lib\site-packages\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
    ...<22 lines>...
    )
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'
